# Generated by Django 3.2.9 on 2022-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
    ]
