# Generated by Django 3.2.9 on 2021-12-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
