# Generated by Django 3.2.9 on 2022-01-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0005_auto_20220103_0511'),
        ('user', '0003_auto_20220103_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annotation',
            field=models.ManyToManyField(to='mark.Annotation'),
        ),
    ]
