# Generated by Django 3.2.9 on 2022-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mid', models.UUIDField(primary_key=True, serialize=False)),
                ('Creator', models.TextField()),
                ('Name', models.TextField()),
                ('Description', models.TextField()),
                ('Participate', models.ManyToManyField(related_name='Participate', to='user.User')),
            ],
        ),
    ]
