# Generated by Django 3.2.9 on 2022-01-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_auto_20220102_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Height',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Width',
            field=models.TextField(),
        ),
    ]
