# Generated by Django 3.2.9 on 2022-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0004_auto_20220103_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='State',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mission',
            name='Tag',
            field=models.ManyToManyField(to='mark.Tag'),
        ),
    ]
