# Generated by Django 3.2.9 on 2022-01-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0005_auto_20220103_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='Point',
        ),
        migrations.RenameField(
            model_name='annotation',
            old_name='Tag',
            new_name='Operations',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='Box',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='Polygon',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
