# Generated by Django 3.2.9 on 2022-01-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_annotation'),
        ('mark', '0006_auto_20220103_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotationstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.BooleanField(default=False)),
                ('Mission', models.ManyToManyField(to='mark.Mission')),
                ('User', models.ManyToManyField(to='user.User')),
            ],
        ),
    ]
